import { useState, useEffect } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { FileText, ChevronRight, Download, ArrowLeft, Loader2, BookOpen, Table as TableIcon } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'

const WikiView = ({ onBack }) => {
  const { t } = useTranslation()
  const [files, setFiles] = useState([])
  const [selectedFile, setSelectedFile] = useState(null)
  const [content, setContent] = useState('')
  const [loading, setLoading] = useState(true)
  const [contentLoading, setContentLoading] = useState(false)
  const [error, setError] = useState(null)

  const apiUrl = import.meta.env.VITE_API_URL

  useEffect(() => {
    fetchFiles()
  }, [])

  const fetchFiles = async () => {
    try {
      setLoading(true)
      const res = await fetch(`${apiUrl}/admin/wiki`)
      if (!res.ok) throw new Error('Failed to fetch wiki pages')
      const data = await res.json()
      setFiles(data)
      if (data.length > 0 && !selectedFile) {
        handleFileSelect(data[0].filename)
      }
    } catch (err) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  const handleFileSelect = async (filename) => {
    try {
      setContentLoading(true)
      setSelectedFile(filename)
      const res = await fetch(`${apiUrl}/admin/wiki/${filename}`)
      if (!res.ok) throw new Error('Failed to fetch page content')
      const data = await res.json()
      setContent(data.content)
    } catch (err) {
      setError(err.message)
    } finally {
      setContentLoading(false)
    }
  }

  const exportToPdf = () => {
    const doc = new jsPDF()
    const title = files.find(f => f.filename === selectedFile)?.title || selectedFile
    
    // Helper to strip emojis and markdown syntax
    const cleanText = (text) => {
      return text
        .replace(/[\u{1F600}-\u{1F64F}\u{1F300}-\u{1F5FF}\u{1F680}-\u{1F6FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}]/gu, '') // Strip emojis
        .replace(/\*\*/g, '') // Strip bold
        .replace(/\*/g, '') // Strip italic
        .replace(/\[([^\]]+)\]\([^\)]+\)/g, '$1') // Strip links but keep text
        .trim()
    }

    // Title
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(22)
    doc.setTextColor(30, 41, 59) // slate-800
    doc.text(cleanText(title), 20, 25)
    
    // Subtitle
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(100, 116, 139) // slate-500
    doc.text(`Resource: ${selectedFile} | Generated by Indeutrade AI`, 20, 32)

    // Divider
    doc.setDrawColor(226, 232, 240) // slate-200
    doc.line(20, 36, 190, 36)
    
    let currentY = 48
    const lines = content.split('\n')
    let textBuffer = []
    let tableBuffer = []
    let inTable = false

    lines.forEach((line) => {
      const trimmedLine = line.trim()
      
      // Skip empty or purely decorative lines
      if (!trimmedLine && !inTable) return

      if (trimmedLine.startsWith('|') && trimmedLine.includes('|')) {
        if (!inTable) {
          flushTextBuffer(doc, textBuffer, currentY, cleanText)
          if (textBuffer.length > 0) {
            currentY = doc.lastAutoTable ? doc.lastAutoTable.finalY + 10 : currentY + (textBuffer.length * 7)
            textBuffer = []
          }
          inTable = true
        }
        tableBuffer.push(line)
      } else {
        if (inTable) {
          const lastTableY = renderPdfTable(doc, tableBuffer, currentY)
          currentY = lastTableY + 12
          tableBuffer = []
          inTable = false
        }

        // Handle Headers
        if (trimmedLine.startsWith('#')) {
          flushTextBuffer(doc, textBuffer, currentY, cleanText)
          if (textBuffer.length > 0) {
            currentY = doc.lastAutoTable ? doc.lastAutoTable.finalY + 10 : currentY + (textBuffer.length * 7)
            textBuffer = []
          }
          
          const level = (trimmedLine.match(/^#+/) || [''])[0].length
          const hText = cleanText(trimmedLine.replace(/^#+\s*/, ''))
          
          if (level === 1) {
            doc.setFont('helvetica', 'bold')
            doc.setFontSize(18)
            doc.setTextColor(15, 23, 42) // slate-900
          } else if (level === 2) {
            doc.setFont('helvetica', 'bold')
            doc.setFontSize(14)
            doc.setTextColor(30, 41, 59) // slate-800
          } else {
            doc.setFont('helvetica', 'bold')
            doc.setFontSize(12)
            doc.setTextColor(51, 65, 85) // slate-700
          }
          
          doc.text(hText, 20, currentY)
          currentY += 10
        } else {
          textBuffer.push(trimmedLine)
        }
      }

      // Page overflow check
      if (currentY > 270) {
        doc.addPage()
        currentY = 25
      }
    })

    // Final flush
    if (inTable) {
      renderPdfTable(doc, tableBuffer, currentY)
    } else {
      flushTextBuffer(doc, textBuffer, currentY, cleanText)
    }
    
    doc.save(`${selectedFile.replace('.md', '')}_export.pdf`)
  }

  const flushTextBuffer = (doc, buffer, currentY, cleanFn) => {
    if (buffer.length === 0) return
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(11)
    doc.setTextColor(71, 85, 105) // slate-600
    const text = buffer.join('\n')
    const splitContent = doc.splitTextToSize(cleanFn(text), 170)
    doc.text(splitContent, 20, currentY)
  }

  const renderPdfTable = (doc, tableBuffer, currentY) => {
    // Basic table row parsing
    const rawRows = tableBuffer.filter(row => row.includes('|') && !row.includes('---'))
    const data = rawRows.map(row => 
      row.split('|')
         .filter((_, i, arr) => i !== 0 && i !== arr.length - 1) // Remove start/end empty cells from split
         .map(cell => cell.trim().replace(/\*\*/g, '')) // Clean cells
    )
    
    const headers = data.shift() || []

    autoTable(doc, {
      head: [headers],
      body: data,
      startY: currentY,
      margin: { left: 20, right: 20 },
      styles: { 
        fontSize: 9, 
        cellPadding: 4,
        font: 'helvetica',
        textColor: [71, 85, 105] 
      },
      headStyles: { 
        fillColor: [30, 41, 59], // slate-800
        textColor: 255, 
        fontStyle: 'bold',
        halign: 'left'
      },
      alternateRowStyles: { 
        fillColor: [248, 250, 252] // slate-50
      },
      columnStyles: {
        0: { fontStyle: 'bold' }
      }
    })
    
    return doc.lastAutoTable.finalY
  }

  // Handle components within markdown for professional look
  const components = {
    a: ({ href, children }) => {
      if (href && href.endsWith('.md')) {
        return (
          <button 
            onClick={() => handleFileSelect(href)}
            className="text-blue-400 hover:text-blue-300 underline decoration-blue-500/30 underline-offset-4 transition-colors"
          >
            {children}
          </button>
        )
      }
      return <a href={href} target="_blank" rel="noopener noreferrer" className="text-blue-400 hover:text-blue-300 underline">{children}</a>
    },
    table: ({ children }) => (
      <div className="my-8 overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/30 backdrop-blur-sm shadow-2xl">
        <table className="w-full text-left border-collapse">
          {children}
        </table>
      </div>
    ),
    thead: ({ children }) => (
      <thead className="bg-slate-800/50 border-b border-slate-700">
        {children}
      </thead>
    ),
    th: ({ children }) => (
      <th className="px-6 py-4 text-xs font-black uppercase tracking-widest text-blue-400">
        {children}
      </th>
    ),
    td: ({ children }) => (
      <td className="px-6 py-4 text-sm text-slate-300 border-b border-slate-800/50">
        {children}
      </td>
    ),
    tr: ({ children }) => (
      <tr className="hover:bg-slate-800/30 transition-colors">
        {children}
      </tr>
    )
  }

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[400px] gap-4">
        <Loader2 className="w-12 h-12 text-blue-500 animate-spin" />
        <p className="text-slate-400 font-medium">{t('common.loading')}</p>
      </div>
    )
  }

  return (
    <div className="flex gap-8 min-h-[calc(100vh-200px)]">
      {/* Wiki Sidebar */}
      <aside className="w-80 flex flex-col gap-4">
        <div className="bg-[#0b1120] border border-slate-800 rounded-3xl p-6 shadow-xl">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 bg-blue-500/10 rounded-2xl flex items-center justify-center">
              <BookOpen className="text-blue-400" size={20} />
            </div>
            <h2 className="text-lg font-bold text-white">Documentation</h2>
          </div>
          
          <div className="space-y-2">
            {files.map((file) => (
              <button
                key={file.filename}
                onClick={() => handleFileSelect(file.filename)}
                className={`w-full flex items-center justify-between p-4 rounded-2xl text-left transition-all group ${
                  selectedFile === file.filename
                    ? 'bg-blue-600 text-white shadow-lg shadow-blue-600/20'
                    : 'bg-slate-900/50 border border-slate-800 text-slate-400 hover:border-slate-700 hover:text-slate-200'
                }`}
              >
                <div className="flex items-center gap-3 truncate">
                  <FileText size={18} className={selectedFile === file.filename ? 'text-blue-200' : 'text-slate-500'} />
                  <span className="font-semibold text-sm truncate">{file.title}</span>
                </div>
                <ChevronRight size={14} className={`shrink-0 transition-transform ${selectedFile === file.filename ? 'translate-x-1' : 'opacity-0 group-hover:opacity-100'}`} />
              </button>
            ))}
          </div>
        </div>

        {onBack && (
          <button
            onClick={onBack}
            className="flex items-center justify-center gap-2 p-4 rounded-2xl bg-slate-800/50 border border-slate-800 text-slate-400 hover:text-white hover:bg-slate-800 transition-all font-bold text-sm"
          >
            <ArrowLeft size={16} />
            {t('common.back')}
          </button>
        )}
      </aside>

      {/* Wiki Content */}
      <main className="flex-1 bg-[#0b1120] border border-slate-800 rounded-[2.5rem] overflow-hidden shadow-2xl flex flex-col">
        <header className="p-8 border-b border-slate-800 flex justify-between items-center bg-slate-900/20">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 bg-blue-500/10 rounded-2xl flex items-center justify-center">
                <BookOpen className="text-blue-400" size={24} />
            </div>
            <div>
                <h1 className="text-2xl font-black text-white tracking-tight">
                {files.find(f => f.filename === selectedFile)?.title || 'Loading...'}
                </h1>
                <p className="text-slate-500 text-[11px] font-bold uppercase tracking-[0.2em] mt-1">
                Node Connection: {selectedFile}
                </p>
            </div>
          </div>
          
          <button
            onClick={exportToPdf}
            disabled={contentLoading}
            className="bg-emerald-600 hover:bg-emerald-700 disabled:opacity-50 text-white px-8 py-3.5 rounded-2xl font-black transition-all shadow-lg shadow-emerald-600/20 flex items-center gap-3 text-xs uppercase tracking-widest"
          >
            <Download size={18} />
            {t('common.export_pdf')}
          </button>
        </header>

        <div className="flex-1 p-10 overflow-y-auto custom-scrollbar">
          {contentLoading ? (
            <div className="flex flex-col items-center justify-center h-full gap-4">
              <Loader2 className="w-8 h-8 text-blue-500 animate-spin" />
              <p className="text-slate-500 text-sm font-medium">Loading content...</p>
            </div>
          ) : (
            <div className="prose prose-invert prose-slate max-w-none 
              prose-headings:text-white prose-headings:font-black prose-headings:tracking-tight
              prose-h1:text-4xl prose-h1:mb-8
              prose-h2:text-2xl prose-h2:mt-12 prose-h2:mb-4 prose-h2:border-b prose-h2:border-slate-800 prose-h2:pb-2
              prose-h3:text-xl prose-h3:mt-8 prose-h3:mb-4
              prose-p:text-slate-400 prose-p:leading-relaxed prose-p:mb-6
              prose-strong:text-blue-400 prose-strong:font-bold
              prose-ul:text-slate-400 prose-li:mb-2
              prose-blockquote:border-l-4 prose-blockquote:border-blue-500 prose-blockquote:bg-blue-500/5 prose-blockquote:p-6 prose-blockquote:rounded-r-2xl prose-blockquote:italic
              prose-hr:border-slate-800 prose-hr:my-12
              prose-code:text-indigo-400 prose-code:bg-slate-900 prose-code:px-2 prose-code:py-0.5 prose-code:rounded-md prose-code:before:content-none prose-code:after:content-none
            ">
              <ReactMarkdown components={components} remarkPlugins={[remarkGfm]}>
                {content}
              </ReactMarkdown>
            </div>
          )}
        </div>
      </main>
    </div>
  )
}

export default WikiView
